# from typing import Tuple

from selenium.webdriver.common.by import By


class LogIn:
    # Main page locators
    learn_more_link = (By.ID, 'learn-more-link')
    back_to_safety_button = (By.ID, 'primary-button')
    SignIn_button = (By.ID, 'procedcheckoutBtn')
    email_textbox = (By.ID, 'user_email')
    email = (By.XPATH, '//*[@id="user_email"]')
    pasw = (By.XPATH, '//*[@id="password"]')
    password_textbox = (By.ID, 'password')
    login_button = (By.ID, 'btn-login')
    login_heading = (By.CLASS_NAME, 'frmheading')
    email_text = (By.XPATH, '//*[@id="apiformprodct"]/div[1]/div/div/div[1]/label')
    password_text = (By.XPATH, '//*[@id="apiformprodct"]/div[1]/div/div/div[2]/label')
    email_field_error = (By.XPATH, '//*[@id="apiformprodct"]/div[1]/div/div/div[1]/label[2]')
    password_field_error = (By.XPATH, '//*[@id="apiformprodct"]/div[1]/div/div/div[2]/label[2]')
    needanaccount_signin = (By.XPATH, '//*[@id="signupformmodal"]/div/div/div[2]/div/div[1]/div/div[1]/p[1]/span')
    ContinueAsGuest_link = (By.XPATH, '//*[@id="gustusrlogin"]/span')
    ForgotPassword_link = (By.XPATH, '//*[@id="apiformprodct"]/div[1]/div/div/div[3]/span/a')
    text_1 = (By.XPATH, '//*[@id="apiformprodct"]/div[1]/div/div/div[4]/span/text()[1]')
    text_2 = (By.XPATH, '//*[@id="apiformprodct"]/div[1]/div/div/div[4]/span/text()[2]')
    privacy_link = (By.XPATH, '//*[@id="apiformprodct"]/div[1]/div/div/div[4]/span/a')
    terms_link = (By.XPATH, '//*[@id="apiformprodct"]/div[1]/div/div/div[4]/span/strong/a')
    home_button = (By.XPATH, '//*[@id="searchhide"]/div[2]/ul/li[1]/a')
    doesnt_match = (By.XPATH, '//*[@id="error"]/div')
    Intro = (By.XPATH, '//*[@id="searchhide"]/div[3]/p[2]/strong/u')
    Terms = (By.XPATH, '//*[@id="searchhide"]/div[3]/p[2]/strong/u')


class ContinueAsGuest:
    ContinueAsGuest_button = (By.XPATH, '//*[@id="gustusrlogin"]/span')
    firstname = (By.NAME, 'fname')
    lastname = (By.NAME, 'lname')
    fullAddress = (By.NAME, 'full_address')
    Apartment = (By.NAME, 'apt')
    MobileNumber = (By.NAME, 'mobile')
    EmailAddress = (By.NAME, 'email')
    submit_button = (By.ID, 'shippingUpprdtcsubbtn')
    signin_button = (By.XPATH, '//*[@id="procedcheckoutBtn"]')
    Shipping_address = (By.XPATH, '//*[@id="loginpanelguess"]/div/span')
    Submit_name = (By.XPATH, '//*[@id="shippingUpprdtcsubbtn"]')
    firstname_error = (By.XPATH, '//*[@id="frmGuestAddress"]/div[1]/label')
    Address_error = (By.XPATH, '//*[@id="frmGuestAddress"]/div[3]/label')
    Mobile_error = (By.XPATH, '//*[@id="frmGuestAddress"]/div[5]/label')
    email_error = (By.XPATH, '//*[@id="frmGuestAddress"]/div[5]/label')
    user_login = (By.XPATH, '//*[@id="signupformmodal"]/div/div/div[2]/div/div[1]/div/div[1]/p[3]/span')
    needanaccount_signin = (By.XPATH, '//*[@id="signupformmodal"]/div/div/div[2]/div/div[1]/div/div[1]/p[1]/span')
    invalid_mobile = (By.XPATH, '//*[@id="frmGuestAddress"]/div[5]/label')
    invalid_Email = (By.XPATH, '//*[@id="frmGuestAddress"]/div[6]/label')
    googleError = (By.XPATH, '//*[@id="street_number2-error"]')


class NeedAnAccount:
    NeedAnAccount_button = (By.XPATH, '//*[@id="signupformmodal"]/div/div/div[2]/div/div[1]/div/div[1]/p[1]/span')
    firname = (By.CSS_SELECTOR, '#reg-form > div:nth-child(2) > input')
    lasname = (By.XPATH, '//*[@id="reg-form"]/div[2]/input')
    enteraddress = (By.XPATH, '//*[@id="autocomplete"]')
    apartmentno = (By.ID, 'apt_no')
    mobileno = (By.XPATH, '//*[@id="reg-form"]/div[5]/input[2]')
    email2 = (By.XPATH, '//*[@id="reg-form"]/div[6]/input')
    pass2 = (By.XPATH, '//*[@id="reg-form"]/div[7]/input')
    ConfirmPassword = (By.NAME, 'confpassword')
    register_button = (By.ID, 'btn-reg')
    signin = (By.XPATH, '//*[@id="procedcheckoutBtn"]')
    registertext = (By.XPATH, '//*[@id="signuppanel"]/div/span')
    firstname_error = (By.XPATH, '//*[@id="reg-form"]/div[1]/label')
    address_error = (By.XPATH, '//*[@id="reg-form"]/div[3]/label')
    mobile_error = (By.XPATH, '//*[@id="reg-form"]/div[5]/label')
    email_error = (By.XPATH, '//*[@id="reg-form"]/div[6]/label')
    password_error = (By.XPATH, '//*[@id="reg-form"]/div[7]/label')
    confirm_password_error = (By.XPATH, '//*[@id="reg-form"]/div[8]/label')
    userlogin_link = (By.XPATH, '//*[@id="signupformmodal"]/div/div/div[2]/div/div[1]/div/div[1]/p[3]/span')
    continue_as_guest_link = (By.XPATH, '//*[@id="gustusrlogin"]/span')
    mobile_invalid = (By.XPATH, '//*[@id="reg-form"]/div[5]/label')
    address_invalid = (By.XPATH, '//*[@id="street_number-error"]')
    email_invalid = (By.XPATH, '//*[@id="reg-form"]/div[6]/label')
    googleError = (By.XPATH, '//*[@id="reg-form"]/div[3]/label')


class ForgetPassword:
    SI_button = (By.XPATH, '//*[@id="procedcheckoutBtn"]')
    ForgetPassword_button = (By.XPATH, '//*[@id="apiformprodct"]/div[1]/div/div/div[3]/span/a')
    registered_email = (By.XPATH, '//*[@id="email"]')
    submit_button = (By.XPATH, '//*[@id="form"]/div[3]/input')
    Uer_login = (By.XPATH, '//*[@id="signupformmodal"]/div/div/div[2]/div/div[1]/div/div[1]/p[3]/span')
    heading1 = (By.XPATH, '//*[@id="searchhide"]/div[10]/div[1]/div[1]/h3')
    heading2 = (By.XPATH, '//*[@id="searchhide"]/div[10]/div[3]/div[1]/h3')
    invalid_email = (By.XPATH, '//*[@id="form"]/div[1]')
    signinbtn = (By.XPATH, '//*[@id="procedcheckoutBtn"]')


class MiniCart:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    click_cart = (By.CLASS_NAME, 'clsCart2')
    ItemCount = (By.XPATH, '//*[@id="minicart"]/div/div[1]/p/span')
    min_order = (By.XPATH, '//*[@id="cartStoreProd"]/div[1]/div/div[1]/div/p[2]')
    proceed_to_checkOut = (By.ID, 'lnkProceedToCheckout')
    checkout2 = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')
    Add1 = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div/div[1]/div[2]/div[2]')
    shop_total = (By.XPATH, '//*[@id="minicart"]/div/div[2]/p[4]')
    image = (By.XPATH, '//*[@id="product"]/div/img')
    NameOfItem = (By.XPATH, '//*[@id="cartStoreProd"]/div[2]/div/div/div[1]/p[1]')
    PriceOfItem = (By.XPATH, '//*[@id="cartStoreProd"]/div[2]/div/div/div[2]/p/span[1]')
    ItemQuantity = (By.XPATH, '//*[@id="qty_cart_270"]/span')
    PlusQuantity = (By.XPATH, '//*[@id="qty_cart_270"]/a[2]')
    MinusQuantity = (By.XPATH, '//*[@id="qty_cart_270"]/a[1]')
    empty_cart = (By.ID, 'lblCartEmpty')
    delete_item = (By.ID, 'lnk_cart_[pid]')
    shop_name = (By.XPATH, '//*[@id="minicart"]/div/div[1]/div/div/div/a')
    shopping_carts = (By.CSS_SELECTOR, '#searchhide > div.clsCartBox > div.clsCartStoresItems > div.clsCartStores > h3')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    LoginButton = (By.XPATH, '//*[@id="btn-login"]')
    SignInButton = (By.XPATH, '//*[@id="procedcheckoutBtn"]')
    additem = (By.XPATH, '//*[@id="img_270"]')
    additem2 = (By.XPATH, '//*[@id="searchhide"]/div[10]/div/section[2]/div/a[1]')
    orderFood = (By.XPATH, '//*[@id="searchhide"]/div[4]/div/div/div/div/a[1]')
    express = (By.XPATH, '//*[@id="load_data"]/div[1]/div[2]')
    item1 = (By.XPATH, '//*[@id="img_270"]')
    item2 = (By.XPATH, '//*[@id="img_616"]')
    additem1 = (By.XPATH, '//*[@id="load_data"]/div[1]/div/div[2]/div/div/div[1]/div/a ')
    addToCart = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/section[2]/div/a[1]')
    clickGrocery = (By.XPATH, '//*[@id="searchhide"]/div[5]/div[1]/div/div/a[2]')
    allStores = (By.XPATH, '//*[@id="stores"]/div/div/a[1]/img')
    shops_name = (By.XPATH, '//*[@id="product"]/div[1]/img')
    shops_name1 = (By.XPATH, '//*[@id="product"]/div[2]/img')
    price_label = (By.XPATH, '//*[@id="stores"]/div/div/a[1]/span[1]')
    count_label = (By.XPATH, '//*[@id="stores"]/div/div/a[1]/span[2]')
    price1 = (By.XPATH, '#stores > div > div > a:nth-child(2) > span.price')
    price2 = (By.XPATH, '#stores > div > div > a:nth-child(3) > span.price')
    CurbsidePickup = (By.CSS_SELECTOR, '#searchhide > div.clsCartBox > div.clsCartStoresItems > div.clsCartItems > div.clsCartSection > a:nth-child(2)')
    Delivery = (By.CSS_SELECTOR,
                '#searchhide > div.clsCartBox > div.clsCartStoresItems > div.clsCartItems > div.clsCartSection > a.active')
    right_arrow = (By.XPATH, '//*[@id="minicart"]/div/div[1]/div/i[2]')
    left_arrow = (By.XPATH, '//*[@id="minicart"]/div/div[1]/div/i[1]')
    ItemInCart = (By.ID, 'lblCartStoreName')
    drop_down1 = (By.XPATH, '//*[@id="qty_270"]')
    drop_down2 = (By.XPATH, '//*[@id="qty_51875"]')
    remove1 = (By.XPATH, '//*[@id="lnk_270"]')
    remove2 = (By.XPATH, '//*[@id="lnk_51875"]')
    eVoucher_label = (By.XPATH, '//*[@id="couponfrm"]/div[1]/div/div[1]/label')
    reward_label = (By.XPATH, '//*[@id="couponfrm"]/div[1]/div/div[2]/label')
    wallet_label = (By.XPATH, '//*[@id="couponfrm"]/div[1]/div/div[3]/label')
    codeOption = (By.XPATH, '//*[@id="parRadioOne"]/p/span')
    maximum_eVoucher = (By.XPATH, '//*[@id="parRadioOne"]/span')
    rewardPoint = (By.XPATH, '//*[@id="parRadioTwo"]/p/span')
    rewardPointApplicable = (By.XPATH, '//*[@id="parRadioTwo"]/span')
    walletBalance = (By.XPATH, '//*[@id="parRadioThree"]/p/span')
    walletEmpty = (By.XPATH, '//*[@id="parRadioThree"]/span')
    orderSummary = (By.CLASS_NAME, 'cartboxttl')
    groceriesSubTotal = (By.CSS_SELECTOR, '#searchhide > div.clsCartBox > div.clsCartOptions > div.cartright-box.cartright-box-two > p:nth-child(2) > span.cartboxitemName.cartboxitemNameBold')
    groceriesItemTotal = (By.XPATH, '//*[@id="lblSubItemsGrocery"]')
    groceriesPrice = (By.XPATH, '//*[@id="lblGrandTotalGrocery"]')
    FoodSubTotal = (By.CSS_SELECTOR, '#searchhide > div.clsCartBox > div.clsCartOptions > div.cartright-box.cartright-box-two > p:nth-child(3) > span.cartboxitemName.cartboxitemNameBold')
    FoodItemTotal = (By.XPATH, '//*[@id="lblSubItemsFood"]')
    FoodPrice = (By.XPATH, '//*[@id="lblGrandTotalFood"]')
    EstimatedTax = (By.XPATH, '//*[@id="tax"]')
    EstimatedTaxPrice = (By.CSS_SELECTOR,
                         '#searchhide > div.clsCartBox > div.clsCartOptions > div.cartright-box.cartright-box-two > p:nth-child(4) > span.cartboxitemPrice')
    EstimatedShipping = (By.XPATH, '//*[@id="shippingfee"]/span[1]')
    EstimatedShippingPrice = (By.XPATH, '//*[@id="shippingfee"]/span[2]')
    MinimumCharge = (By.XPATH, '//*[@id="storemincharge"]')
    MinimumChargePrice = (By.CSS_SELECTOR,
                          '#searchhide > div.clsCartBox > div.clsCartOptions > div.cartright-box.cartright-box-two > p:nth-child(6) > span.cartboxitemPrice')
    PackageHandling = (By.XPATH, '//*[@id="pkgcharge"]')
    PackageHandlingPrice = (By.CSS_SELECTOR,
                            '#searchhide > div.clsCartBox > div.clsCartOptions > div.cartright-box.cartright-box-two > p:nth-child(7) > span.cartboxitemPrice')
    Tip = (By.CSS_SELECTOR,
           '#searchhide > div.clsCartBox > div.clsCartOptions > div.cartright-box.cartright-box-two > p.cartboxitemtip > span.cartboxitemName')
    TipPrice = (By.XPATH, '//*[@id="tip"]')
    EstimatedOrder = (By.CSS_SELECTOR,
                      '#shippingfee > span.cartboxitemName')
    EstimatedOrderPrice = (By.XPATH, '//*[@id="tipadd"]')
    DeliveryLabel = (By.CSS_SELECTOR,
                     '#searchhide > div.clsCartBox > div.clsCartOptions > div.cartright-box.cartright-box-three > p.addrslbl > span')
    ChangeAddress = (By.XPATH, '//*[@id="changeAddrssBtn"]')
    EstimatedDelivery = (By.CSS_SELECTOR, '#deliverystate > strong')
    DeliveryNotes = (By.CSS_SELECTOR,
                     '#searchhide > div.clsCartBox > div.clsCartOptions > div.cartright-box.cartright-box-three > div.delivery_notesbox-wrapper > label > b')
    ProceedToPayment = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div[2]/div[2]')
    InvalidCoupon = (By.XPATH, '//*[@id="parRadioOne"]/div')
    drop_quantity = (By.XPATH, '//*[@id="qty_51875"]/option[2]')
    eVoucher = (By.CSS_SELECTOR, '#vocherRewardWallet-1')
    reward = (By.XPATH, '//*[@id="vocherRewardWallet-2"]')
    wallet = (By.XPATH, '//*[@id="vocherRewardWallet-3"]')
    eVoucher_text = (By.XPATH, '//*[@id="e-vouchercode"]')
    reward_text = (By.XPATH, '//*[@id="e-vouchercode"]')
    NoTip = (By.XPATH, '//*[@id="tipzero"]')
    Tip5 = (By.XPATH, '//*[@id="tipthree"]')
    Tip10 = (By.XPATH, '//*[@id="tipfive"]')
    Tip15 = (By.XPATH, '//*[@id="tipseven"]')
    Tip20 = (By.XPATH, '//*[@id="tipten"]')
    clickCross = (By.XPATH, '')
    Notes_text = (By.XPATH, '//*[@id="delivery_notesbox"]')
    Apply = (By.XPATH, '//*[@id="parRadioOne"]/a')
    paypal = (By.XPATH, '//*[@id="paymentbox"]/div/div/div[2]/div/a/img')
    signIn = (By.ID, 'procedcheckoutBtn')
    shopNow = (By.XPATH, '//*[@id="subscribe"]/div/div/div[2]/form/button')
    secondShop = (By.XPATH, '/html/body/div[1]/div[1]/div/div[2]/div[1]/div[2]/div[1]/div/div[1]/div/p[1]')
    SecondItemName = (By.CSS_SELECTOR, '#product > div:nth-child(2) > div.clsDetails > p')
    SecondItemPrice = (By.CSS_SELECTOR, '#product > div:nth-child(2) > div.clsDetails > div > span:nth-child(1)')
    SecondItemQuanitity = (By.XPATH, '//*[@id="qty_cart_51875"]/span')
    yourAccount = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/span')
    ChangePaymentMethod = (By.XPATH, '//*[@id="choose-payment-method"]')
    AddPaymentMethod = (By.XPATH, '/html/body/div[2]/div/div/div[1]/div[1]/div[2]/div[2]/span')
    CreditCardNumber = (By.XPATH, '//*[@id="credit-card-number"]')
    Expiration = (By.ID, 'expiration')
    CVV = (By.ID, 'cvv')
    Pay = (By.ID, 'pay_amount')
    Payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    Department = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]')
    GroceryShop = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[1]/a')
    crossButton = (By.XPATH, '//*[@id="paymentbox"]/div/div/div[1]/button')
    quicklly = (By.XPATH, '/html/body/header/a/img')
    orderID = (By.XPATH, '//*[@id="innerlist-products"]/strong"')
    accountName = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/p')
    eVoucher_text_value = (By.XPATH, '//*[@id="e-vouchercode"]')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    GoFresh = (By.XPATH, '//*[@id="searchhide"]/div[7]/div[1]/div/div/a[2]/img')
    clickCredit = (By.XPATH, '//*[@id="container"]/div[1]/div/div[2]/div/form/label')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    HitSearch = (By.XPATH, '//*[@id="searchbtn"]')


class Coupon:
    zipCode = (By.XPATH, '//*[@id="zipcode"]')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    submit_zip = (By.ID, 'zipsubmitbtn')
    enter_zip = (By.ID, 'zipcode')
    submitButton = (By.XPATH, '//*[@id="zipsubmitbtn"]')
    yourAccount = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/span')
    SignInButton = (By.XPATH, '//*[@id="procedcheckoutBtn"]')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    LoginButton = (By.XPATH, '//*[@id="btn-login"]')
    additem = (By.XPATH, '//*[@id="img_270"]')
    additem2 = (By.XPATH, '//*[@id="load_data"]/div[1]/div/div/div/div[2]/div/a')
    click_cart = (By.CLASS_NAME, 'clsCart2')
    proceed_to_checkOut = (By.ID, 'lnkProceedToCheckout')
    evoucher_text_box = (By.XPATH, '//*[@id="e-vouchercode"]')
    InvalidCoupon = (By.XPATH, '//*[@id="load_data"]/div[1]/div/div/div/div[4]/a')
    Apply = (By.XPATH, '//*[@id="parRadioOne"]/a')
    empty_cart = (By.ID, 'lblCartEmpty')
    GoFresh = (By.XPATH, '//*[@id="searchhide"]/div[7]/div[1]/div/div/a[2]/img')
    item1 = (By.XPATH, '//*[@id="load_data"]/div/div/div/div/div[1]/a')
    addToCart = (By.XPATH, '//*[@id="searchhide"]/div[5]/div/section[2]/div/a[1]')
    checkout2 = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')


class Department:
    enter_zip = (By.ID, 'zipcode')
    instantPot = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[4]/h1')
    submit_zip = (By.ID, 'zipsubmitbtn')
    yourAccount = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/span')
    SignInButton = (By.XPATH, '//*[@id="procedcheckoutBtn"]')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    LoginButton = (By.XPATH, '//*[@id="btn-login"]')
    proceed_to_checkOut = (By.ID, 'lnkProceedToCheckout')
    additem = (By.XPATH, '//*[@id="img_270"]')
    ProceedtoCheckout = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')
    Pay = (By.ID, 'pay_amount')
    Pot = (By.XPATH, '//*[@id="searchhide"]/div[10]/div/div/div/div/a[17]/img')
    Department = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/span')
    select = (By.XPATH, '//*[@id="nationwide"]/div[2]/div[1]/a')
    Add = (By.XPATH, '//*[@id="img_77024"]')
    AddToCart = (By.XPATH, '//*[@id="searchhide"]/div[2]/div/div[2]/div[3]/a[2]')
    quicklly = (By.XPATH, '//*[@id="searchhide"]/header/a/img')
    right_arrow = (By.XPATH, '//*[@id="minicart"]/div/div[1]/div/i[2]')
    Seeti = (By.XPATH, '//*[@id="minicart"]/div/div[1]/div/div/div/a[3]')
    delete = (By.XPATH, '//*[@id="lnk_cart_[pid]"]')
    GoFresh = (By.XPATH, '//*[@id="searchhide"]/div[12]/div[1]/div/div/a[2]/img')
    labelJasneet = (By.XPATH, '//*[@id="tiffin-services"]/div/div[2]/h3')
    labelShika = (By.XPATH, '//*[@id="tiffin-services"]/div/div[3]/h3')
    labelShilpa = (By.XPATH, '//*[@id="tiffin-services"]/div/div[4]/h3')
    AddToCartLG = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/section[2]/div/a[1]')
    addSecondItem = (By.XPATH, '//*[@id="img_51875"]')
    AddToCartP = (By.XPATH, '//*[@id="searchhide"]/div[10]/div/section[2]/div/a[1]')
    # food = (By.XPATH, '//*[@id="searchhide"]/div[10]/div/div/div/div/a[5]/img')
    food = (By.XPATH, '//*[@id="searchhide"]/div[1]/div/div/div/div/a[5]/img')
    MakkiFastFood = (By.XPATH, '//*[@id="load_data"]/div[2]/a')
    AddTenders = (By.XPATH, '//*[@id="load_data"]/div[2]/div/div[2]/a')
    TendersAddToCart = (By.XPATH, '//*[@id="dvDialog-Custom"]/div/div[2]/a')
    submitTenders = (By.XPATH, '//*[@id="dvDialog-DateTime"]/div/div[2]/a')
    payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    BBQKit = (By.XPATH, '//*[@id="searchhide"]/div[4]/div/div/div/div/a[3]/img')
    chickenTikkaImage = (By.XPATH, '//*[@id="img_132523"]')
    AddTikkaToCart = (By.XPATH, '//*[@id="searchhide"]/div[2]/div/div/div[2]/div[2]/div[1]/div[2]/div/a')
    # Catering = (By.XPATH, '//*[@id="searchhide"]//img[@alt="Catering"]')
    Catering = (By.XPATH, "//*[@id='searchhide']//a[@class='slick-slide']//img[@alt='Catering']")
    HyderabadHouse = (By.XPATH, '//*[@id="Catering"]/div/div[1]/a')
    AddBeefFry = (By.CSS_SELECTOR, '#searchhide > div.clsFoodStore > div > div > div:nth-child(1) > a')
    AddToCartBeef = (By.XPATH, '//*[@id="dvDialog-Custom"]/div/div[2]/a')
    submitBeef = (By.XPATH, '//*[@id="dvDialog-DateTime"]/div/div[2]/a')
    mealBasket = (By.XPATH, '/html/body/div[1]/div[5]/div/div/div/div/a[11]/img')
    MealPlan = (By.XPATH, '//*[@id="meal-basket"]/div[2]/div[1]/a')
    AddKorma = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[1]/div[1]/div[3]/div[3]/a')
    plusKorma = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[1]/div[1]/p/a/span[3]')
    AddToCartCK = (By.XPATH, '//*[@id="searchhide"]/div[2]/p/span[2]/a')
    TiffinServices = (
        By.CSS_SELECTOR, '#searchhide > div.grocerySpecialSlider.clsFoodSpl.clslowspace > div > div > div > div > a:nth-child(8) > img')
    ChicagoTiffin = (By.XPATH, '//*[@id="tiffin-services"]/div/div[1]/a')
    VegThali = (By.XPATH, '//*[@id="TiffinServices"]/div[2]/div[1]/a')
    AddToCartVegThali = (By.XPATH, '//*[@id="dvDialog-Custom"]/div/div[2]/a')
    submitVT = (By.XPATH, '//*[@id="dvDialog-DateTime"]/div/div[2]/a')
    MealKit = (By.XPATH, '/html/body/header/div[2]/div/div[1]/div[1]/div/div/ul/li[9]/a')
    CuminClub = (By.XPATH, '//*[@id="home"]/div/div[4]/div/a/div/img')
    MakkahCafe = (By.XPATH, '//*[@id="load_data"]/div[7]/a')
    GorkahChicken = (By.XPATH, ' // *[ @ id = "load_data"] / div[1] / h3')
    AddaIndian = (By.XPATH, ' //*[@id="load_data"]/div[2]/h3')
    Kabobchi = (By.XPATH, ' //*[@id="load_data"]/div[3]/h3')
    CafeAlif = (By.XPATH, ' //*[@id="load_data"]/div[4]/h3')
    AromaDesi = (By.XPATH, '//*[@id="load_data"]/div[5]/h3')
    AaloSamosa2 = (By.XPATH, '//*[@id="load_data"]/div[2]/div/div[2]/h3')
    ChilliBeef = (By.XPATH, '//*[@id="load_data"]/div[7]/div/div[2]/h3')
    BeefTaco = (By.XPATH, '//*[@id="load_data"]/div[12]/div/div[2]/h3')
    Tikka = (By.XPATH, ' //*[@id="load_data"]/div[25]/div/div[2]/h3')
    Biryani = (By.XPATH, '//*[@id="load_data"]/div[29]/div/div[2]/h3')

    Aloosam = (By.XPATH, '//*[@id="load_data"]/div[2]/div/div[2]/a')
    submitAlooSam = (By.XPATH, '//*[@id="dvDialog-DateTime"]/div/div[2]/a')
    selectMealKit = (By.XPATH, '//*[@id="meal-kit"]/div[2]/div[1]/form/a')
    AddPapad = (By.XPATH, '/html/body/div[5]/div/div/div[1]/div[3]/div[3]/a')
    plusPapad = (By.XPATH, '/html/body/div[6]/div/div/div[1]/p/a/span[3]')
    AddToCartPapad = (By.XPATH, '//*[@id="searchhide"]/div[2]/p/span[3]/a')
    Recipes = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[8]/a')
    PalakPaneer = (By.XPATH, '//*[@id="45"]/img')
    AddToBasket = (By.XPATH, '//*[@id="addchekListprodct"]')
    delivery = (By.XPATH, '//*[@id="ddlDeliveryTime"]')
    timeDelivery = (By.XPATH, '#ddlDeliveryTime > option:nth-child(3)')
    clickTick = (By.XPATH, '//*[@id="flexCheckDefault"]')
    clickRA = (By.XPATH, '//*[@id="searchhide"]/div[5]/div/div/i[2]/img')
    OrganicGrocery = (By.XPATH, '//*[@id="searchhide"]/div[4]/div/div/div/div/a[5]/img')
    BuildABox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[4]/form/button')
    AddOrganicJowar = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/div/div[1]/div[3]/div[1]/a')
    AddToCartOrganic = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div/div[3]/button')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    Account = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/span')
    Account2 = (By.XPATH, '/html/body/header/div[3]/span')
    Hyderabadlabel = (By.XPATH, '//*[@id="Catering"]/div/div[1]/h3')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    IndianCatering = (By.XPATH, '//*[@id="searchhide"]/div[2]/ul/li[2]/h1')
    # LeftArrow = (By.XPATH, '//*[@id="searchhide"]/div[9]/div/div/i[1]/img')
    LeftArrow = (By.XPATH, '//*[@id="searchhide"]/div[1]/div/div/i[1]/img')
    rightArrow = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/i[2]/img')
    rotiKIt = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[7]/img')
    buildRotiBox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[4]/form/button')
    AddWholeWheatRoti = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/div/div[1]/div[3]/div[2]/a')
    AddToCartRoti = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div/div[3]/button')
    checkout2 = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')
    liquorStore = (By.XPATH, '//*[@id="searchhide"]//img[@alt="Online Liquor Store"]')
    # liquorStore = (By.XPATH, '//*[@id="searchhide"]/div[10]/div/div/div/div/a[2]/img')
    Beer = (By.XPATH, '//*[@id="searchhide"]//img[@alt="Beer"]')
    classicLime = (By.XPATH, '//*[@id="img_138002"]')
    AddToCartLime = (By.XPATH, '//*[@id="storeproductlist"]/div/div[2]/a')
    Becks12 = (By.XPATH, '//*[@id="img_137801"]')
    AddtoCartBecks12 = (By.XPATH, '//*[@id="storeproductlist"]/div/div[2]/a')
    ChaiAndCoffee = (By.XPATH, '/html/body/div[1]/div[5]/div/div/div/div/a[4]/img')
    ChaiBox = (By.XPATH, '/html/body/div[4]/section[1]/div/div/div[2]/div[4]/form/button')
    AddKimbala = (By.XPATH, '/html/body/div[6]/div[3]/div/div/div[1]/div[3]/div/a')
    NationWideShop = (
        By.CSS_SELECTOR,
        '#searchhide > div.grocerySpecialSlider.clsFoodSpl.clslowspace > div > div > div > div > a:nth-child(6) > img')
    IndianMealKit = (By.XPATH,'//*[@id="home"]/div/div[11]/div/a/div/div/h3')
    SelectProducts = (By.XPATH, '/html/body/div[4]/section[1]/div/div/div[1]/div/div[5]/form/button')
    AddMixVegetable = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[1]/div[3]/a')
    AddMisalPav = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[2]/div[3]/a')
    PlusMixVegetable = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[1]/div[3]/p/a/span[3]')
    AddToCartNW = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[2]/button')
    MethaiPaneer = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[3]/div[3]/a')
    DalTadka = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[4]/div[3]/a')
    PlusDalTadka = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[4]/div[3]/p/a/span[3]')
    legalCheckBox = (By.XPATH, '/html/body/div[6]/div/div[1]/p[1]/label/input')
    elderCheckBox = (By.XPATH, '/html/body/div[6]/div/div[1]/p[2]/label/input')
    submitALcohol = (By.XPATH, '/html/body/div[6]/div/div[2]/a')
    searchBox = (By.XPATH, '//*[@id="search_box"]')
    searchButton = (By.ID, 'searchbtn')
    Sauces = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[4]/h1')


class ZipCode:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    quicklly = (By.XPATH, '//*[@id="searchhide"]/header/a/img')
    grocery = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[1]/a')
    food = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[2]/a')
    BBQKit = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[3]/a')
    RotiKit = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[4]/a')
    Catering = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[5]/a')
    organicGrocery = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[6]/a')
    MealBasket = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[7]/a')
    TiffinServices = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[8]/a')
    MealKit = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[9]/a')
    InstantPot = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[10]/a')
    Recipes = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[8]/a')
    department = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/span')
    cross = (By.XPATH, '//*[@id="popupoffer"]/div/div/div/div/button/img')
    list = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]/div/div/ul')


class Contact:
    enter_zip = (By.ID, 'zipcode')
    contact = (By.LINK_TEXT, 'CONTACT')
    name = (By.ID, 'name')
    email = (By.ID, 'email')
    subject = (By.ID, 'mobile')
    comment = (By.ID, 'comment')
    send = (By.XPATH, '//*[@id="main-contact-form"]/div/fieldset/ul/div/button')
    thanks = (By.XPATH, '//*[@id="messages_product_view"]/p')


class SignUp:
    enter_zip = (By.ID, 'zipcode')
    signin = (By.XPATH, '//*[@id="procedcheckoutBtn"]')
    needAccount = (By.XPATH, '//*[@id="signupformmodal"]/div/div/div[2]/div/div[1]/div/div[1]/p[1]/span')
    firstName = (By.XPATH, '//*[@id="reg-form"]/div[1]/input')
    lastName = (By.XPATH, '//*[@id="reg-form"]/div[2]/input')
    Address = (By.XPATH, '//*[@id="autocomplete"]')
    Phone = (By.XPATH, '//*[@id="reg-form"]/div[5]/input[2]')
    email = (By.XPATH, '//*[@id="reg-form"]/div[6]/input')
    password = (By.XPATH, '//*[@id="reg-form"]/div[7]/input')
    confirmpassword = (By.XPATH, '//*[@id="reg-form"]/div[8]/input')
    register = (By.XPATH, '//*[@id="btn-reg"]')
    email2 = (By.XPATH, '//*[@id="user_email"]')
    password2 = (By.XPATH, '//*[@id="password"]')
    logIn = (By.XPATH, '//*[@id="btn-login"]')
    heading = (By.XPATH, '/html/body/div[2]/h2')


class Refer:
    refer = (By.XPATH, '/html/body/header/div/div[2]/a')
    referLink = (By.XPATH, '/html/body/header/div/div[2]/div/div/ul/li[1]/a')
    clickFacebook = (By.XPATH, '//*[@id="referfb"]')
    facebookLink = (By.XPATH, '//*[@id="shareonFacebookBtn"]')
    clickTwitter = (By.XPATH, '//*[@id="refertw"]')
    twitterLink = (By.XPATH, '//*[@id="shareonTwitterBtn"]')


class GuestCheckout:
    enter_zip = (By.ID, 'zipcode')
    goFresh = (By.XPATH, '//*[@id="searchhide"]/div[8]/div[1]/div/div/a[2]/img')
    potatoImage = (By.XPATH, '//*[@id="img_51875"]')
    AddtoCart = (By.XPATH, '//*[@id="searchhide"]/div[7]/div/section[2]/div/a[1]')
    Cart = (By.XPATH, '//*[@id="searchhide"]/header/div[4]/a')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    guest = (By.XPATH, '//*[@id="gustusrlogin"]/span')
    Fname = (By.XPATH, '//*[@id="frmGuestAddress"]/div[1]/input')
    Lname = (By.XPATH, '//*[@id="frmGuestAddress"]/div[2]/input')
    Address = (By.XPATH, '//*[@id="autocomplete2"]')
    number = (By.XPATH, '//*[@id="frmGuestAddress"]/div[5]/input[2]')
    email = (By.XPATH, '//*[@id="frmGuestAddress"]/div[6]/input')
    submit = (By.XPATH, '//*[@id="shippingUpprdtcsubbtn"]')
    submit_zip = (By.ID, 'zipsubmitbtn')
    checkout2 = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')
    shoppingCarts = (By.XPATH, '//*[@id="lblCartStoreName"]')
    searchBox = (By.XPATH, '//*[@id="search_box"]')
    searchButton = (By.ID, 'searchbtn')


class Category:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    UnbeatableDeals = (By.XPATH, '//*[@id="searchhide"]/div[7]/div[1]/div/div/a[1]/img')
    GoFresh = (By.XPATH, '//*[@id="searchhide"]/div[7]/div[1]/div/div/a[2]/img')
    Grocery = (By.XPATH, '//*[@id="searchhide"]/div[7]/div[1]/div/div/a[3]/img')
    Meat = (By.XPATH, '//*[@id="searchhide"]/div[7]/div[1]/div/div/a[4]/img')
    Beverages = (By.XPATH, '//*[@id="searchhide"]/div[8]/div[1]/div/div/a[5]/span')
    Organic = (By.XPATH, '//*[@id="searchhide"]/div[7]/div[1]/div/div/a[6]/img')
    PersonalCare = (By.XPATH, '//*[@id="searchhide"]/div[7]/div[1]/div/div/a[7]/img')
    Household = (By.XPATH, '//*[@id="searchhide"]/div[7]/div[1]/div/div/a[8]/img')
    StoreLabel = (By.XPATH, '//*[@id="store-detail-name"]')
    weeklyDeals = (By.XPATH, '//*[@id="searchhide"]/div[8]/div[2]/div/div/a[1]')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')


class Links:
    facebook = (By.LINK_TEXT, 'FACEBOOK')
    twitter = (By.LINK_TEXT, 'TWITTER')
    linkedin = (By.LINK_TEXT, 'LINKEDIN')
    youtube = (By.LINK_TEXT, 'YOUTUBE')
    instagram = (By.LINK_TEXT, 'INSTAGRAM')
    pinterest = (By.LINK_TEXT, 'PINTEREST')
    fbLabel = (By.CSS_SELECTOR, '#blueBarDOMInspector > div > div > div > div.lfloat._ohe > a > i > u')
    tweetLabel = (By.XPATH,
                  '//*[@id="react-root"]/div/div/div[2]/main/div/div/div/div/div/div[2]/div/div/nav/div/div[2]/div/div[1]/a/div')
    linkedinLabel = (By.CSS_SELECTOR, 'body > div > main > div > form > h1')
    youtubeLabel = (By.XPATH, '//*[@id="img"]')
    instagramSRC = (By.XPATH, '//*[@id="react-root"]/section/nav/div[2]/div/div/div[1]/a/div/div/img')
    pinterestLabel = (By.CSS_SELECTOR, '#mweb-unauth-container > div > div.Jea.fZz.jzS.snW.wsz.zI7.iyn.Hsu > div > div > div:nth-child(1) > div.Pj7.sLG.XiG.OVX.m1e > div > img')


class Invalid:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')


class GuestLogin:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    food = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[3]/img')
    MakkiFastFood = (By.XPATH, '//*[@id="load_data"]/div[2]/a')
    AddTenders = (By.XPATH, '//*[@id="load_data"]/div[2]/div/div[2]/a')
    TendersAddToCart = (By.XPATH, '//*[@id="dvDialog-Custom"]/div/div[2]/a')
    submitTenders = (By.XPATH, '//*[@id="dvDialog-DateTime"]/div/div[2]/a')
    guest = (By.XPATH, '//*[@id="gustusrlogin"]/span')
    Fname = (By.XPATH, '//*[@id="frmGuestAddress"]/div[1]/input')
    Lname = (By.XPATH, '//*[@id="frmGuestAddress"]/div[2]/input')
    Address = (By.XPATH, '//*[@id="autocomplete2"]')
    number = (By.XPATH, '//*[@id="frmGuestAddress"]/div[5]/input[2]')
    email = (By.XPATH, '//*[@id="frmGuestAddress"]/div[6]/input')
    checkout2 = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')
    submit = (By.XPATH, '//*[@id="shippingUpprdtcsubbtn"]')
    Pay = (By.ID, 'pay_amount')
    cardNumber = (By.XPATH, '//*[@id="container"]/div[1]/div/div[2]/div/form/label')
    expirationDate = (By.XPATH, '//*[@id="container"]/div[1]/div/div[2]/div/form/div/div[1]/label')
    CVV = (By.XPATH, '//*[@id="cvv"]')
    quicklly = (By.XPATH, '//*[@id="searchhide"]/header/a/img')
    LeftArrow = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/i[1]/img')
    Catering = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[14]/img')
    HyderabadHouse = (By.XPATH, '//*[@id="Catering"]/div/div[1]/a')
    AddBeefFry = (By.CSS_SELECTOR, '#searchhide > div.clsFoodStore > div > div > div:nth-child(1) > a')
    AddToCartBeef = (By.XPATH, '//*[@id="dvDialog-Custom"]/div/div[2]/a')
    submitBeef = (By.XPATH, '//*[@id="dvDialog-DateTime"]/div/div[2]/a')
    delivery = (By.XPATH, '//*[@id="ddlDeliveryTime"]')
    timeDelivery = (By.XPATH, '//*[@id="ddlDeliveryTime"]/option[2]')
    TiffinServices = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[5]/img')
    ChicagoTiffin = (By.XPATH, '//*[@id="tiffin-services"]/div/div[1]/a')
    VegThali = (By.XPATH, '//*[@id="TiffinServices"]/div[2]/div[1]/a')
    AddToCartVegThali = (By.XPATH, '//*[@id="dvDialog-Custom"]/div/div[2]/a')
    submitVT = (By.XPATH, '//*[@id="dvDialog-DateTime"]/div/div[2]/a')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')


class Payment:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    yourAccount = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/span')
    SignInButton = (By.XPATH, '//*[@id="procedcheckoutBtn"]')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    LoginButton = (By.XPATH, '//*[@id="btn-login"]')
    proceed_to_checkOut = (By.ID, 'lnkProceedToCheckout')
    Account = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/span')
    GoFresh = (By.XPATH, '//*[@id="searchhide"]/div[12]/div[1]/div/div/a[2]')
    additem = (By.XPATH, '//*[@id="img_270"]')
    AddToCartLG = (By.XPATH, '//*[@id="searchhide"]/div[10]/div/section[2]/div/a[1]')
    payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    Pay = (By.ID, 'pay_amount')
    checkout2 = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')
    choosePayment = (By.ID, 'choose-payment-method')
    AddMethod = (By.CSS_SELECTOR,
                 'body > div.modal-wrap > div > div > div.modal-container > div.list-payment-methods-view.modal-frame-view.render-in-assemble > div.modal-body-content > div.add-payment-method-item > span')
    cardNumber = (By.XPATH, '//*[@id="credit-card-number"]')
    expiry = (By.XPATH, '//*[@id="expiration"]')
    CVV = (By.XPATH, '//*[@id="cvv"]')
    savePaymentMethod = (By.XPATH, '/html/body/div[2]/div/div/div[1]/div[2]/div[3]/div[1]/button')
    AddMethod2 = (By.XPATH, '/html/body/div[2]/div/div/div[1]/div[2]/div[3]/button')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    loginLabel = (By.XPATH, '//*[@id="apiformprodct"]/div[1]/span')


class SignUpCheckout:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    yourAccount = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/span')
    SignInButton = (By.XPATH, '//*[@id="procedcheckoutBtn"]')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    LoginButton = (By.XPATH, '//*[@id="btn-login"]')
    proceed_to_checkOut = (By.ID, 'lnkProceedToCheckout')
    additem = (By.XPATH, '//*[@id="img_270"]')
    Pay = (By.ID, 'pay_amount')
    Pot = (By.XPATH, '/html/body/div[1]/div[5]/div/div/div/div/a[12]/img')
    Department = (By.XPATH, '//*[@id="searchhide"]/header/div[2]/div/div[1]/div[1]')
    select = (By.XPATH, '//*[@id="nationwide"]/div[2]/div[1]/a')
    Add = (By.XPATH, '//*[@id="img_77024"]')
    AddToCart = (By.XPATH, '//*[@id="searchhide"]/div[2]/div/div[2]/div[3]/a[2]')
    quicklly = (By.XPATH, '//*[@id="searchhide"]/header/a/img')
    right_arrow = (By.XPATH, '//*[@id="minicart"]/div/div[1]/div/i[2]')
    Seeti = (By.XPATH, '//*[@id="minicart"]/div/div[1]/div/div/div/a[3]')
    delete = (By.XPATH, '//*[@id="lnk_cart_[pid]"]')
    GoFresh = (By.XPATH, '//*[@id="searchhide"]/div[8]/div[1]/div/div/a[2]/img')
    AddToCartLG = (By.XPATH, '//*[@id="searchhide"]/div[7]/div/section[2]/div/a[1]')
    addSecondItem = (By.XPATH, '//*[@id="img_51875"]')
    AddToCartP = (By.XPATH, '//*[@id="searchhide"]/div[7]/div/section[2]/div/a[1]')
    food = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[3]/img')
    MakkiFastFood = (By.XPATH, '//*[@id="load_data"]/div[2]/a')
    AddTenders = (By.XPATH, '//*[@id="load_data"]/div[2]/div/div[2]/a')
    TendersAddToCart = (By.XPATH, '//*[@id="dvDialog-Custom"]/div/div[2]/a')
    submitTenders = (By.XPATH, '//*[@id="dvDialog-DateTime"]/div/div[2]/a')
    payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    BBQKit = (By.XPATH, '//*[@id="searchhide"]/div[4]/div/div/div/div/a[3]/img')
    chickenTikkaImage = (By.XPATH, '//*[@id="img_132523"]')
    AddTikkaToCart = (By.XPATH, '//*[@id="searchhide"]/div[2]/div/div/div[2]/div[2]/div[1]/div[2]/div/a')
    Catering = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[14]/img')
    HyderabadHouse = (By.XPATH, '//*[@id="Catering"]/div/div[1]/a')
    AddBeefFry = (By.XPATH, '//*[@id="searchhide"]/div[5]/div/div/div[1]/a')
    AddToCartBeef = (By.XPATH, '//*[@id="dvDialog-Custom"]/div/div[2]/a')
    submitBeef = (By.XPATH, '//*[@id="dvDialog-DateTime"]/div/div[2]/a')
    mealBasket = (By.XPATH, '/html/body/div[1]/div[5]/div/div/div/div/a[11]/img')
    MealPlan = (By.XPATH, '//*[@id="meal-basket"]/div[2]/div[1]/a')
    AddKorma = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[1]/div[1]/div[3]/div[3]/a')
    plusKorma = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[1]/div[1]/p/a/span[3]')
    AddToCartCK = (By.XPATH, '//*[@id="searchhide"]/div[2]/p/span[2]/a')
    TiffinServices = (
        By.CSS_SELECTOR,
        '#searchhide > div.grocerySpecialSlider.clsFoodSpl > div > div > div > div > a:nth-child(6) > img')
    ChicagoTiffin = (By.XPATH, '//*[@id="tiffin-services"]/div/div[1]/a')
    VegThali = (By.XPATH, '//*[@id="TiffinServices"]/div[2]/div[1]/a')
    AddToCartVegThali = (By.XPATH, '//*[@id="dvDialog-Custom"]/div/div[2]/a')
    submitVT = (By.XPATH, '//*[@id="dvDialog-DateTime"]/div/div[2]/a')
    MealKit = (By.XPATH, '/html/body/header/div[2]/div/div[1]/div[1]/div/div/ul/li[9]/a')
    CuminClub = (By.XPATH, '//*[@id="home"]/div/div[4]/div/a/div/img')
    selectMealKit = (By.XPATH, '//*[@id="meal-kit"]/div[2]/div[1]/form/a')
    AddPapad = (By.XPATH, '/html/body/div[5]/div/div/div[1]/div[3]/div[3]/a')
    plusPapad = (By.XPATH, '/html/body/div[6]/div/div/div[1]/p/a/span[3]')
    AddToCartPapad = (By.XPATH, '//*[@id="searchhide"]/div[2]/p/span[3]/a')
    Recipes = (By.XPATH, '/html/body/div[1]/header/div[2]/div/div[1]/div[1]/div/div/ul/li[9]/a')
    PalakPaneer = (By.XPATH, '//*[@id="45"]/img')
    AddToBasket = (By.XPATH, '//*[@id="addchekListprodct"]')
    delivery = (By.XPATH, '//*[@id="ddlDeliveryTime"]')
    timeDelivery = (By.XPATH, '//*[@id="ddlDeliveryTime"]/option[2]')
    clickTick = (By.XPATH, '//*[@id="flexCheckDefault"]')
    clickRA = (By.XPATH, '//*[@id="searchhide"]/div[5]/div/div/i[2]/img')
    OrganicGrocery = (By.XPATH, '//*[@id="searchhide"]/div[4]/div/div/div/div/a[5]/img')
    BuildABox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[4]/form/button')
    AddOrganicJowar = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/div/div[1]/div[3]/div[1]/a')
    AddToCartOrganic = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div/div[3]/button')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    Account = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/span')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    LeftArrow = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/i[1]/img')
    rightArrow = (By.XPATH, '//*[@id="searchhide"]/div[1]/div/div/i[2]/img')
    rotiKIt = (By.XPATH, '/html/body/div[1]/div[5]/div/div/div/div/a[7]/img')
    buildRotiBox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[4]/form/button')
    AddWholeWheatRoti = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/div/div[1]/div[3]/div[2]/a')
    AddToCartRoti = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div/div[3]/button')
    checkout2 = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')
    liquorStore = (By.XPATH, '/html/body/div[1]/div[5]/div/div/div/div/a[2]/img')
    Beer = (By.XPATH, '//*[@id="searchhide"]/section[1]/div[2]/div/div/div[1]/a/img')
    classicLime = (By.XPATH, '//*[@id="img_138002"]')
    AddToCartBeer = (By.XPATH, '/html/body/div[5]/div[2]/div[2]/div[2]/div[2]/div[2]/a')
    ChaiAndCoffee = (By.XPATH, '/html/body/div[1]/div[5]/div/div/div/div/a[4]/img')
    ChaiBox = (By.XPATH, '/html/body/div[4]/section[1]/div/div/div[2]/div[4]/form/button')
    AddKimbala = (By.XPATH, '/html/body/div[6]/div[3]/div/div/div[1]/div[3]/div/a')
    NationWideShop = (By.XPATH, '//*[@id="searchhide"]/div[5]/div/div/div/div/a[5]/img')
    IndianMealKit = (By.XPATH, '/html/body/div[1]/div[7]/div[2]/div/div/div[1]/div/div[1]/div/a/div/img')
    SelectProducts = (By.XPATH, '/html/body/div[4]/section[1]/div/div/div[1]/div/div[5]/form/button')
    AddMixVegetable = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[1]/div[3]/a')
    AddMisalPav = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[2]/div[3]/a')
    PlusMixVegetable = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[1]/div[3]/p/a/span[3]')
    AddToCartNW = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[2]/button')
    MethaiPaneer = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[3]/div[3]/a')
    DalTadka = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[4]/div[3]/a')
    PlusDalTadka = (By.XPATH, '/html/body/div[5]/section[3]/div/div/div[1]/div[4]/div[3]/p/a/span[3]')
    legalCheckBox = (By.XPATH, '/html/body/div[6]/div/div[1]/p[1]/label/input')
    elderCheckBox = (By.XPATH, '/html/body/div[6]/div/div[1]/p[2]/label/input')
    submitALcohol = (By.XPATH, '/html/body/div[6]/div/div[2]/a')
    searchBox = (By.XPATH, '//*[@id="search_box"]')
    searchButton = (By.ID, 'searchbtn')
    signin = (By.XPATH, '//*[@id="procedcheckoutBtn"]')
    needAccount = (By.XPATH, '//*[@id="signupformmodal"]/div/div/div[2]/div/div[1]/div/div[1]/p[1]/span')
    firstName = (By.XPATH, '//*[@id="reg-form"]/div[1]/input')
    lastName = (By.XPATH, '//*[@id="reg-form"]/div[2]/input')
    Address = (By.XPATH, '//*[@id="autocomplete"]')
    Phone = (By.XPATH, '//*[@id="reg-form"]/div[5]/input[2]')
    email = (By.XPATH, '//*[@id="reg-form"]/div[6]/input')
    password = (By.XPATH, '//*[@id="reg-form"]/div[7]/input')
    confirmpassword = (By.XPATH, '//*[@id="reg-form"]/div[8]/input')
    register = (By.XPATH, '//*[@id="btn-reg"]')
    cardNumber = (By.XPATH, '//*[@id="container"]/div[1]/div/div[2]/div/form/label')
    expirationDate = (By.XPATH, '//*[@id="container"]/div[1]/div/div[2]/div/form/div/div[1]/label')
    CVV = (By.XPATH, '//*[@id="cvv"]')


class ChaiAndCoffee:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    heading1 = (By.XPATH, '//*[@id="searchhide"]/div/div/ul/li[3]/h1')
    weekly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[2]')
    weeklyLabel = (By.XPATH, '//*[@id="weekly"]/div[2]/p[2]')
    BiWeekly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[3]')
    monthly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[4]')
    Once = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[1]')
    BiWeeklyLabel = (By.XPATH, '//*[@id="bi-weekly"]/div[2]/p[2]')
    monthlyLabel = (By.XPATH, '//*[@id="monthly"]/div[2]/p[2]')
    OnceLabel = (By.CLASS_NAME, 'tblinkfree')
    buildABox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[4]/form/button')
    indianChaiLabel = (By.XPATH, '//*[@id="searchhide"]/div[1]/ul/li[4]/h1')
    backToChaiCoffee = (By.XPATH, '/html/body/div[5]/ul/li[2]/a')
    subscription = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[1]/h2')
    collection = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[1]/h3')
    ChaiAssamica = (By.XPATH, ' //*[@id="searchhide"]/div[3]/div[1]/div[2]/ul/div/div/li[2]/a/span')
    CoffeeJaggery = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[1]/div[2]/ul/div/div/li[3]/a/span')
    coffeeNeat = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[1]/div[2]/ul/div/div/li[4]/a/span')
    ChaiConcentrate = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[1]/div[2]/ul/div/div/li[5]/a/span')
    DirtyChai = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[1]/div[2]/ul/div/div/li[6]/a/span')
    readyChai = (By.XPATH, '//*[@id="searchhide"]/section[3]/div/div[2]/div/h2')
    readyCoffee = (By.XPATH, '//*[@id="searchhide"]/section[4]/div/div[2]/div/h2')
    aboutKimbala = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[3]/div/div/div[1]/div[1]/h3')
    aboutRTD = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[3]/div/div/div[2]/div[1]/h3')
    aboutDirty = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[3]/div/div/div[4]/div[1]/h3')
    aboutConcrete = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[3]/div/div/div[3]/div[1]/h3')
    aboutKimbala2 = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[3]/div/div/div[5]/div[1]/h3')
    aboutRTD2 = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[3]/div/div/div[10]/div[1]/h3')
    aboutRTD3 = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[3]/div/div/div[12]/div[1]/h3')
    Pay = (By.ID, 'pay_amount')
    Payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    quicklly = (By.XPATH, '/html/body/header/a/img')
    MinimumOrder = (By.XPATH, '//*[@id="cartStoreProd"]/div[1]/div/div/div/p[2]')

class MealKit:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    MealKitLabel = (By.XPATH, '//*[@id="searchhide"]/div[10]/ul/li[2]/h1')
    Explore = (By.CSS_SELECTOR, '#searchhide > div.container.meal-kit-heading > div:nth-child(1) > div > h2')
    popular = (By.XPATH, '//*[@id="profile-tab"]')
    IBK = (By.XPATH, '//*[@id="profile"]/div/div[7]/div/a/div/div/p')
    new = (By.XPATH, '//*[@id="home-tab"]')
    IndianSeasoningLabel = (By.XPATH, '//*[@id="home"]/div/div[5]/div/a/div/div/h3')
    whyChooseLabel = (By.XPATH, '//*[@id="myTabContent"]/div[3]/div/h2')
    AuthenticLabel = (By.XPATH,
                      '#myTabContent > div.card-container.row.why-choose-us-box.slick-initialized.slick-slider > div > div > div.meal-kit-box.col-sm-4.slick-slide.slick-current.slick-active.slick-center > div > div > div > h3')
    subscribeAndSave = (By.CSS_SELECTOR,
                        '#myTabContent > div.card-container.row.why-choose-us-box.slick-initialized.slick-slider > div > div > div.meal-kit-box.col-sm-4.slick-slide.slick-current.slick-active.slick-center > div > div > div > h3')
    FreeShipping = (By.XPATH, '//*[@id="myTabContent"]/div[4]/div/div/div[5]/div/div/img')
    CantGetEnough = (By.XPATH, '//*[@id="myTabContent"]/div[5]/div/h4')
    groceries = (By.XPATH, '//*[@id="myTabContent"]/div[6]/div[1]/a/div/div[2]/img')
    food = (By.XPATH, '//*[@id="myTabContent"]/div[6]/div[2]/a/div/div[2]/img')
    catering = (By.XPATH, '//*[@id="myTabContent"]/div[6]/div[3]/a/div/div[2]/img')
    mealbasket = (By.XPATH, '//*[@id="myTabContent"]/div[6]/div[4]/a/div/div[2]/img')
    indianGrocery = (By.XPATH, '//*[@id="store-lising-main-bread-crumb"]/ul/li[2]/h1')
    indianFood = (By.XPATH, '//*[@id="searchhide"]/div[2]/ul/li[2]/h1')
    indianCatering = (By.XPATH, '//*[@id="searchhide"]/div[2]/ul/li[2]/h1')
    tiffinWala = (By.XPATH, '//*[@id="searchhide"]/div[2]/ul/li[3]/h1')
    tiffin = (By.XPATH, '//*[@id="myTabContent"]/div[6]/div[5]/a/div/div[2]/img')
    mealKit = (By.XPATH, '//*[@id="myTabContent"]/div[6]/div[6]/a/div/div[2]/img')
    instantPot = (By.XPATH, '//*[@id="myTabContent"]/div[6]/div[7]/a/div/div[2]/img')
    recipes = (By.XPATH, '//*[@id="myTabContent"]/div[6]/div[8]/a/div/div[2]/img')
    organic = (By.XPATH, '//*[@id="myTabContent"]/div[6]/div[9]/a/div/div/img')
    chai = (By.XPATH, '//*[@id="myTabContent"]/div[6]/div[10]/a/div/div/img')
    indianMealKit = (By.XPATH, '//*[@id="myTabContent"]/div[6]/div[11]/a/div/div/img')
    indianTiffin = (By.XPATH, '//*[@id="searchhide"]/div[2]/ul/li[2]/h1')
    mealStores = (By.XPATH, '//*[@id="searchhide"]/div[10]/ul/li[2]/h1')
    instantLabel = (By.XPATH, '//*[@id="searchhide"]/div[2]/ul/li[2]/h1')
    recipesLabel = (By.XPATH, '//*[@id="nav-tabContent"]/div[1]/ul/li[2]/h1')
    organicLabel = (By.XPATH, '//*[@id="searchhide"]/div/div/ul/li[2]/h1')
    chaiLabel = (By.XPATH, '//*[@id="searchhide"]/div/div/ul/li[2]/h1')
    indianMeal = (By.XPATH, '//*[@id="searchhide"]/div/div/ul/li[2]/h1')
    home = (By.XPATH, '//*[@id="store-lising-main-bread-crumb"]/ul/li[1]/a')


class IndianSeasoningKit:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    indianSeasoning = (By.XPATH, '//*[@id="home"]/div/div[3]/div/a/div/img')
    IndianSeasoningLabel = (By.XPATH, '//*[@id="searchhide"]/div[2]/ul/li[3]/h1')
    chooseyourmenu = (By.XPATH, '//*[@id="searchhide"]/div[3]/h2/b')
    flavours = (By.XPATH, '//*[@id="meal-kit"]/div[2]/div/div/div[1]/h2')
    labelSeasoning = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[2]/ul/div/div/li[2]/a')
    labelEasybowl = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[2]/ul/div/div/li[3]/a/text()')
    labelSignature = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[2]/ul/div/div/li[4]/a/text()')
    labelSpices = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[2]/ul/div/div/li[5]/a/text()')
    labelWholespices = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[2]/ul/div/div/li[6]/a/text()')
    labelChilipowder = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div/div[1]/div[3]/h3')
    labelKashmiri = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div/div[2]/div[3]/h3')
    labelCurrypowder = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div/div[3]/div[3]/h3')
    labelCuminpowder = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div/div[4]/div[3]/h3')
    labelSpicycchicken = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div/div[5]/div[3]/h3')
    blackPepperImage = (By.XPATH, '//*[@id="meal-kit"]/div[2]/div/div/div[2]/ul/li[1]/img')
    startFLowerImage = (By.XPATH, '//*[@id="meal-kit"]/div[2]/div/div/div[2]/ul/li[2]/img')
    ElaichiImage = (By.XPATH, '//*[@id="meal-kit"]/div[2]/div/div/div[2]/ul/li[3]/img')
    turmericImage = (By.XPATH, '//*[@id="meal-kit"]/div[2]/div/div/div[2]/ul/li[4]/img')
    nutmegImage = (By.XPATH, '//*[@id="meal-kit"]/div[2]/div/div/div[2]/ul/li[5]/img')
    CuminSeedImage = (By.XPATH, '//*[@id="meal-kit"]/div[2]/div/div/div[2]/ul/li[6]/img')
    ISL = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[1]/div[2]/div/div[2]/h2')
    easyIndieBowls = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div/div[2]/h2')
    weekly = (By.XPATH, '//*[@id="seasn1"]/div[1]/center/ul/li[2]')
    BiWeekly = (By.XPATH, '//*[@id="seasn1"]/div[1]/center/ul/li[3]')
    Monthly = (By.XPATH, '//*[@id="seasn1"]/div[1]/center/ul/li[4]')
    Once = (By.XPATH, '//*[@id="seasn1"]/div[1]/center/ul/li[1]')
    weekly2 = (By.XPATH, '//*[@id="seasn1"]/div[2]/center/ul/li[2]')
    BiWeekly2 = (By.XPATH, '//*[@id="seasn1"]/div[2]/center/ul/li[3]')
    monthly2 = (By.XPATH, '//*[@id="seasn1"]/div[2]/center/ul/li[4]')
    once2 = (By.XPATH, '//*[@id="seasn1"]/div[2]/center/ul/li[1]')
    seasoningKitLabel = (By.XPATH, '//*[@id="seasn1"]/div[1]/h3')
    EasyIndianLabel = (By.XPATH, '//*[@id="seasn1"]/div[2]/h3')
    selectProducts = (By.XPATH, '//*[@id="seasonings-kit"]/a')
    selectProducts2 = (By.XPATH, '//*[@id="easyindebowl"]/a')
    OrderSeasoningKit = (By.XPATH, '/html/body/div[11]/ul/li[4]/h1')
    ClickSeasoningkit = (By.XPATH, '//*[@id="seasonings-kit"]/a')
    clickIndian = (By.XPATH, '/html/body/div[5]/ul/li[2]/a')
    labelEasy = (By.XPATH, '/html/body/div[8]/ul/li[3]/h1')
    Pay = (By.ID, 'pay_amount')
    Payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    quicklly = (By.XPATH, '/html/body/header/a/img')
    ProceedtoCheckout = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')
    IndianSubscription = (By.XPATH, '//*[@id="searchhide"]/div[2]/ul/li[3]/h1')



class IndianGroceryBox:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    indianGrocery = (By.XPATH, '//*[@id="searchhide"]/div[9]/div/div/div/div/a[13]/img')
    indianGroceryLabel = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[1]/h2')
    subscription = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[1]/h2')
    labelFlour = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[2]/ul/div/div/li[2]/a')
    labelMillets = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[2]/ul/div/div/li[3]/a')
    labelPulses = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[2]/ul/div/div/li[5]/a')
    labelRice = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[2]/ul/div/div/li[6]/a')
    labelSpices = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[2]/ul/div/div/li[7]/a')
    labelRaggi = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/div/div[1]/div[1]/a/h3')
    labelAtta = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/div/div[2]/div[1]/a/h3')
    labelMillets2 = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/div/div[3]/div[1]/a/h3')
    labelBajra = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/div/div[4]/div[1]/a/h3')
    shipping = (By.XPATH, '//*[@id="weekly"]/div[1]/p[1]')
    minimum = (By.XPATH, '//*[@id="weekly"]/div[2]/p[1]')
    free = (By.XPATH, '//*[@id="weekly"]/div[1]/p[2]')
    cost = (By.XPATH, '//*[@id="weekly"]/div[2]/p[2]')
    whatwedeliver = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[1]/h3')
    Authentic = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div[1]/div/div[1]/h4')
    Unbeatable = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div[1]/div/div[2]/h4')
    customized = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div[1]/div/div[3]/h4')
    HowItWorks = (By.XPATH, '//*[@id="searchhide"]/section[3]/div[1]/h3')
    build = (By.XPATH, '//*[@id="searchhide"]/section[3]/div[2]/div[2]/h4')
    selectProducts = (By.XPATH, '//*[@id="searchhide"]/section[3]/div[3]/div[2]/h4')
    frequency = (By.XPATH, '//*[@id="searchhide"]/section[3]/div[4]/div[2]/h4')
    order = (By.XPATH, '//*[@id="searchhide"]/section[4]/div/div[1]/div/h2')
    weekly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[1]')
    BiWeekly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[2]')
    Monthly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[3]')
    Once = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[4]')
    buildABox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[4]/form/button')
    organicProducts = (By.XPATH, '//*[@id="searchhide"]/div[1]/div/ul/li[4]/h1')
    OIG = (By.XPATH, '//*[@id="searchhide"]/div[1]/div/ul/li[2]/a')
    turmericPowder = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/div/div[1]/div[3]/div[1]/a')
    Pay = (By.ID, 'pay_amount')
    Payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    quicklly = (By.XPATH, '/html/body/header/a/img')
    AddToCart = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div/div[3]/button')
    ProceedtoCheckout = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')


class RotiKit:
    enter_zip = (By.ID, 'zipcode')
    ProceedtoCheckout = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    IndianRotiKit = (By.XPATH, '//*[@id="home"]/div/div[6]/div/a/div/img')
    RotiLabel = (By.XPATH, '//*[@id="searchhide"]/div/div/ul/li[3]/h1')
    categories = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[1]')
    WholeWheat = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[1]/a/img')
    wholewheatlabel = (By.XPATH, '//*[@id="load_data"]/div[16]/div[1]')
    FreshTawa = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[2]/a/img')
    FreshTawaLabel = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[2]/div/a/h3')
    Roti = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[2]/a/img')
    rotiLabel = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[2]/div/a/h3')
    MultiGrain = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[3]/a/img')
    MultiGrainLabel = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[4]/div/a/h3')
    Rotla = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[4]/a/img')
    RotlaLabel = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[6]/div/a/h3')
    Paratha = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[5]/a/img')
    ParathaLabel = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[5]/div/a/h3')
    Thepla = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[7]/a/img')
    TheplaLabel = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[7]/div/a/h3')
    SpecialRoti = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[6]/a/img')
    SpecialRotiLabel = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[7]/div/a/h3')
    Bakhri = (By.XPATH, '//*[@id="img_135321"]')
    BakhriLabel = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[9]/div/a/h3')
    GLutenFree = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[10]/a/img')
    GLutenFreeLabel = (By.XPATH, '//*[@id="searchhide"]/section[2]/div[2]/div/div[10]/div/a/h3')
    whatweDeliver = (By.XPATH, '//*[@id="searchhide"]/section[4]/div[1]/h3')
    WhatareRotis = (By.XPATH, '//*[@id="searchhide"]/section[5]/div/div[2]/div/h2')
    FreshHomeMade = (By.XPATH, '//*[@id="searchhide"]/section[4]/div[2]/div[1]/div/div[1]/h4')
    Premium = (By.XPATH, '//*[@id="searchhide"]/section[4]/div[2]/div[1]/div/div[2]/h4')
    FreeDeivery = (By.XPATH, '//*[@id="searchhide"]/section[4]/div[2]/div[1]/div/div[3]/h4')
    weekly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[2]')
    BiWeekly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[3]')
    Monthly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[4]')
    Once = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[1]')
    FreeDeiveryOnMinimumOrder = (By.XPATH, '//*[@id="one-time"]/div[2]/p[1]')
    IndianBread = (By.XPATH, '//*[@id="searchhide"]/div[1]/ul/li[4]/h1')
    OrderRotiKit = (By.XPATH, '//*[@id="searchhide"]/div[1]/div/ul/li[2]/a')
    buildABox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[4]/form/button')
    Pay = (By.ID, 'pay_amount')
    Payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    quicklly = (By.XPATH, '/html/body/header/a/img')

class IndianMealKit:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    indianmealKit = (By.XPATH, '//*[@id="home"]/div/div[2]/div/a/div/img')
    indianSubscription = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[4]/h1')
    # indianSubscription2 = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[4]/h1')
    # indianSubscription3 = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[4]/h1')
    chooseMEal = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/h2')
    readyToEat = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[1]/div/div[1]/h2')
    shipping = (By.XPATH, '//*[@id="one-time"]/div[1]/p[1]')
    free = (By.XPATH, '//*[@id="one-time"]/div[1]/p[2]')
    price = (By.XPATH, '//*[@id="one-time"]/div[2]/p[1]')
    dryPacked = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div/div[1]/h2')
    howItWorks = (By.XPATH, '//*[@id="searchhide"]/section[2]/div/div[1]/h3')
    selectMeal = (By.XPATH, '//*[@id="searchhide"]/section[2]/div/div[2]/div/div[1]/div/a/h3')
    cookAndDeliver = (By.XPATH, '//*[@id="searchhide"]/section[2]/div/div[2]/div/div[2]/div/a/h3')
    eatAndEnjoy = (By.XPATH, '//*[@id="searchhide"]/section[2]/div/div[2]/div/div[3]/div/a/h3')
    OurProducts = (By.XPATH, '//*[@id="searchhide"]/section[3]/h2')
    enjoyTheComfort = (By.XPATH, '//*[@id="searchhide"]/section[5]/div/div[2]/div/h2')
    weekly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[1]/div/div[2]/ul/li[2]')
    BiWeekly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[1]/div/div[2]/ul/li[3]')
    Monthly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[1]/div/div[2]/ul/li[4]')
    Once = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[1]/div/div[2]/ul/li[1]')
    weekly2 = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div/div[2]/ul/li[2]')
    BiWeekly2 = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div/div[2]/ul/li[3]')
    monthly2 = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div/div[2]/ul/li[4]')
    once2 = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div/div[2]/ul/li[1]')
    selectProducts = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[1]/div/div[5]/form/button')
    selectProducts2 = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div/div[5]/form/button')
    SubscriptionBox = (By.XPATH, '//*[@id="searchhide"]/div[1]/ul/li[3]/h1')
    IMKS = (By.XPATH, '//*[@id="searchhide"]/div[1]/ul/li[2]/a')
    Pay = (By.ID, 'pay_amount')
    Payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    quicklly = (By.XPATH, '/html/body/header/a/img')
    BhindiMasala = (By.XPATH, '//*[@id="searchhide"]/section[3]/div/div/div[1]/div[1]/div[3]/a')
    selectStore = (By.ID, 'selctProductStore')
    curryBox = (By.XPATH, '//*[@id="selctProductStore"]/option[2]')
    selectDate = (By.XPATH, '//*[@id="ddlDeliveryDateChange"]')
    chooseDate = (By.XPATH, '//*[@id="ddlDeliveryDateChange"]/option[2]')
    ProceedtoCheckout = (By.XPATH, '//*[@id="dvFoodSuggestPopup"]/div/div/a')
    IndianMealKitDelivery = (By.XPATH, '//*[@id="searchhide"]/div[2]/ul/li[3]/h1')
class IndianMealKitAndSauces:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    Sauces = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[4]/h1')
    Shopseeti = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[2]/h2')
    Biryani = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div/div[1]/div[1]/a/h3')
    Paneer = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div/div[2]/div[1]/a/h3')
    Curry = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div/div[3]/div[1]/a/h3')
    ChannaMasala = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div/div[6]/div[1]/a/h3')
    ButterChicken = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div/div[11]/div[1]/a/h3')
    Mistress = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div/div[7]/div[1]/a/h3')
    MasMeat = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div/div[4]/div[1]/a/h3')
    Palak = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div/div[5]/div[1]/a/h3')
    instantPot = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[4]/h1')
    explore = (By.XPATH, '//*[@id="searchhide"]/div[3]/h2')
    sauces = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[4]/h1')
    mealKit = (By.XPATH, '//*[@id="nationwide"]/div[2]/div[2]/h3')
    effortless = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[3]/h2[1]')
    step1 = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[3]/div[1]/div[1]/p')
    step2 = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[3]/div[1]/div[2]/p')
    step3 = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[3]/div[1]/div[3]/p')
    step4 = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[3]/div[1]/div[4]/p')
    fromFridge = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[3]/div[1]/div[1]/span')
    setPan = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[3]/div[1]/div[2]/span')
    relax = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[3]/div[1]/div[3]/span')
    enjoy = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[3]/div[1]/div[4]/span')
    OurFoodPhilosophy = (By.XPATH, '//*[@id="searchhide"]/div[3]/div/div[3]/h2[2]')
    delivery = (By.XPATH, '//*[@id="nationwide"]/div[1]')
    nationwide = (By.XPATH, '//*[@id="searchhide"]/div[3]/ul/li[1]/a')
    BayArea = (By.XPATH, '//*[@id="searchhide"]/div[3]/ul/li[2]/a')
    select = (By.XPATH, '//*[@id="nationwide"]/div[2]/div[1]/a')
    select1 = (By.XPATH, '//*[@id="nationwide"]/div[2]/div[2]/a')
    saucesLabel = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[4]/h1')
    backToPage = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[3]/a')
    mealKitLabel = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[4]/h1')
    Eat = (By.XPATH, '//*[@id="bay-shop"]/div[2]/div[1]/h3')
    vegetarian = (By.XPATH, '//*[@id="bay-shop"]/div[2]/div[2]/h3')
    vegan = (By.XPATH, '//*[@id="bay-shop"]/div[2]/div[3]/h3')
    NutFree = (By.XPATH, '//*[@id="bay-shop"]/div[2]/div[4]/h3')
    s = (By.XPATH, '//*[@id="bay-shop"]/div[2]/div[5]/h3')
    clickEat = (By.XPATH, '//*[@id="bay-shop"]/div[2]/div[1]/a')
    clickVegetarian = (By.XPATH, '//*[@id="bay-shop"]/div[2]/div[2]/a')
    clickVegan = (By.XPATH, '//*[@id="bay-shop"]/div[2]/div[3]/a')
    clickNutfree = (By.XPATH, '//*[@id="bay-shop"]/div[2]/div[4]/a')
    clickBay = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[3]/a')
    Shahi = (By.XPATH, '//*[@id="searchhide"]/div[3]/div[2]/div/div[1]/div[2]/div/a')
    Pay = (By.ID, 'pay_amount')
    Payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    quicklly = (By.XPATH, '/html/body/header/a/img')

class BBQ:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    bbqKit = (By.XPATH, '//*[@id="home"]/div/div[9]/div/a/div/img')
    bbqLabel = (By.XPATH, '//*[@id="searchhide"]/div[1]/div/ul/li[3]/h1')
    chilling = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[1]/h2')
    menu = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[2]/h3')
    AllGrills = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/ul/li[1]/a')
    VegGrills = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/ul/li[2]/a')
    NonVeg = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[3]/ul/li[3]/a')
    Tandoori = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[1]/div[1]/a/h3')
    ChickenTikka = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[2]/div[1]/a/h3')
    reshmi = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[3]/div[1]/a/h3')
    Aloo = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[4]/div[1]/a/h3')
    hariyaliChicken = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[5]/div[1]/a/h3')
    hariyaliPaneer = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[6]/div[1]/a/h3')
    PaneerTikka = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[7]/div[1]/a/h3')
    TandooriChicken = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[8]/div[1]/a/h3')
    Lamb = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[9]/div[1]/a/h3')
    BotiKabaab = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[10]/div[1]/a/h3')
    OurFood = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div[2]/h2')
    MinimumOrder = (By.XPATH, '//*[@id="cartStoreProd"]/div[1]/div/div/div/p[2]')
    clickFive = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[1]/div[2]/ul/li[2]/label/input')
    clickEight = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[1]/div[2]/ul/li[1]/label/input')
    Price = (By.XPATH, '//*[@id="searchhide"]/div[2]/div[4]/div/div[1]/div[1]/span')
    Pay = (By.ID, 'pay_amount')
    Payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')

class OneTime:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    NationWideShop = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[6]/img')
    indianSweet = (By.XPATH, '//*[@id="home"]/div/div[2]/div/a/div/img')
    buildAbox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[5]/form/button')
    addMasalaMathai = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/a')
    plusMasalaMathai = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/p/a/span[3]')
    AddToCart = (By.XPATH, '//*[@id="v-bar-fixed"]/div[2]/button[2]')
    Rajbogh = (By.XPATH, '//*[@id="load_data"]/div/div[1]')
    Cart = (By.XPATH, '/html/body/header/div[4]/a')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    Pay = (By.ID, 'pay_amount')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    quantity = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/p/a/span[2]')
    logout = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/div/div/ul/li[6]/a')

class Weekly:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    NationWideShop = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[6]/img')
    indianSweet = (By.XPATH, '//*[@id="home"]/div/div[2]/div/a/div/img')
    buildAbox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[5]/form/button')
    addMasalaMathai = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/a')
    plusMasalaMathai = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/p/a/span[3]')
    Rajbogh = (By.XPATH, '//*[@id="load_data"]/div/div[1]')
    IndianMealKitDelivery = (By.XPATH, '//*[@id="searchhide"]/div[2]/ul/li[3]/h1')
    indianSubscription = (By.XPATH, '//*[@id="searchhide"]/div[1]/div[1]/ul/li[4]/h1')
    AddToCart = (By.XPATH, '//*[@id="v-bar-fixed"]/div[2]/button[2]')
    Cart = (By.XPATH, '/html/body/header/div[4]/a')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    Pay = (By.ID, 'pay_amount')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    quantity = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/p/a/span[2]')
    logout = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/div/div/ul/li[6]/a')
    weekly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[2]')

class BiWeekly:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    NationWideShop = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[6]/img')
    indianSweet = (By.XPATH, '//*[@id="home"]/div/div[2]/div/a/div/img')
    buildAbox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[5]/form/button')
    addMasalaMathai = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/a')
    plusMasalaMathai = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/p/a/span[3]')
    AddToCart = (By.XPATH, '//*[@id="v-bar-fixed"]/div[2]/button[2]')
    Cart = (By.XPATH, '/html/body/header/div[4]/a')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    Pay = (By.ID, 'pay_amount')
    Email = (By.ID, 'user_email')
    Rajbogh = (By.XPATH, '//*[@id="load_data"]/div/div[1]')
    Pass = (By.ID, 'password')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    quantity = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/p/a/span[2]')
    logout = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/div/div/ul/li[6]/a')
    BiWeekly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[3]')

class Monthly:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    NationWideShop = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[6]/img')
    indianSweet = (By.XPATH, '//*[@id="home"]/div/div[2]/div/a/div/img')
    buildAbox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[5]/form/button')
    addMasalaMathai = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/a')
    plusMasalaMathai = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/p/a/span[3]')
    AddToCart = (By.XPATH, '//*[@id="v-bar-fixed"]/div[2]/button[2]')
    Rajbogh = (By.XPATH, '//*[@id="load_data"]/div/div[1]')
    Cart = (By.XPATH, '/html/body/header/div[4]/a')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    Pay = (By.ID, 'pay_amount')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    quantity = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/p/a/span[2]')
    logout = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/div/div/ul/li[6]/a')
    Monthly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[4]')

class Maximum:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    NationWideShop = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[6]/img')
    indianSweet = (By.XPATH, '//*[@id="home"]/div/div[2]/div/a/div/img')
    buildAbox = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[5]/form/button')
    addMasalaMathai = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/a')
    plusMasalaMathai = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/p/a/span[3]')
    AddToCart = (By.XPATH, '//*[@id="v-bar-fixed"]/div[2]/button[2]')
    Cart = (By.XPATH, '/html/body/header/div[4]/a')
    Rajbogh = (By.XPATH, '//*[@id="load_data"]/div/div[1]')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    Pay = (By.ID, 'pay_amount')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    quantity = (By.XPATH, '//*[@id="load_data"]/div[1]/div[4]/p/a/span[2]')
    logout = (By.XPATH, '//*[@id="searchhide"]/header/div[3]/div/div/ul/li[6]/a')
    Monthly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[4]')

class Edit:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    SearchForProducts1 = (By.XPATH, '// *[ @ id = "searchhide"] / div / div / ul / li[3] / h1')
    NationWideShop = (By.XPATH, '//*[@id="searchhide"]/div[6]/div/div/div/div/a[6]/img')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    Rajbogh = (By.XPATH, '//*[@id="load_data"]/div/div[1]')
    Monthly = (By.XPATH, '//*[@id="searchhide"]/section[1]/div/div/div[2]/div[2]/ul/li[4]')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    Pay = (By.ID, 'pay_amount')




class CommonLocators:
    learn_more_link = (By.ID, 'learn-more-link')
    main_loader = (By.XPATH, '/html/body/header/a/img')

    buttons = (By.XPATH, '//button[@type="submit"]')
    main_heading = (By.XPATH, '//h3')
    table = (By.XPATH, "//table")
    table_xpath = '(//table)[{}]'
    xpath_head = (By.XPATH, "//table[contains(@class,'table')]//th")
    heading_xpath = '(//table[contains(@class,"table")])[{}]//th'
    next_page = (By.XPATH, '//table//a[@aria-label="Next page"]')
    next_page_xpath = '(//table)[{}]//a[@aria-label="Next page"]'
    success_toast_msg = (By.XPATH, "//div[contains(@class,'alert-success')]")
    global_toast_message = (By.XPATH, '//*[local-name()="global-messages"]//div[contains(@class,"alert-")]')
    toast_message_close_button = (By.XPATH, '//*[local-name()="global-messages"]//button')
    table_headings = (By.XPATH, '//thead//th')
    add_button = (By.XPATH, '//span[contains(@class,"btn btn-primary pull-right")]')
    ng_spinner = (By.XPATH, '//div[contains(@class, "ng-spinner-loader")]')
    alert_2 = (By.XPATH, '//*[local-name()="global-messages"]//div[contains(@role,"alert")]')
    spinner = (By.XPATH, '//app-activity-indicator/..')
    verification_textbox = (By.XPATH, '//app-password-verification//input')
    verification_confirm_button = (By.XPATH, '//app-password-verification//button[contains(@class,"btn-primary")]')
    verification_cancel_button = (By.XPATH, '//app-password-verification//button[contains(@class,"cancel_button")]')
    next_page_button = (By.XPATH, '//a[@aria-label="Next page"]')
    # main_loader = (By.XPATH, '//app-activity-indicator//div[@id="loader"]')
    sub_page_loader = (By.XPATH, '//app-spinner')


class PrivacyErrorPageLocators:
    # Privacy Error Page Locators
    learn_more_link = (By.ID, 'learn-more-link')
    err_cert_common_name_invalid = (By.ID, 'error-code')
    improve_chrome_security_checkbox = (By.ID, 'opt-in-checkbox')
    advanced_button = (By.ID, 'details-button')
    proceed_link = (By.ID, 'proceed-link')
    back_to_safety_button = (By.ID, 'primary-button')

class AddRecipient:
    FName = (By.XPATH, '//*[@id="recipient_fname"]')
    LName = (By.XPATH, '//*[@id="recipient_lname"]')
    Email = (By.ID, 'recipient_email')
    PhoneNo = (By.ID, 'recipient_phone')
    Address = (By.XPATH, '//*[@id="autocomplete4"]')
    ApartmentNo = (By.XPATH, '//*[@id="recipient_appartment"]')
    Delieverytype = (By.XPATH, '//*[@id="frmRecipent"]/div[1]/div/div[7]/div[1]/p/input')
    SubmitButton = (By.ID, 'save_recipent')

class evoucher:
    enter_zip = (By.ID, 'zipcode')

class Diwali_Kit:
    enter_zip = (By.ID, 'zipcode')
    submit_zip = (By.ID, 'zipsubmitbtn')
    submit_zip1 = (By.ID, 'dvDialogMomentss')
    SearchForProducts = (By.XPATH, '//*[@id="search_box"]')
    GiftBasketLabel = (By.XPATH, '//*[@id="searchhide"]/div[1]/div/ul/li[3]/h1')
    Pay = (By.ID, 'pay_amount')
    Payment = (By.XPATH, '//*[@id="proceedtopayment"]')
    checkout = (By.XPATH, '//*[@id="lnkProceedToCheckout"]')
    ThankYou = (By.XPATH, '//*[@id="innerlist-products"]/h1')
    Email = (By.ID, 'user_email')
    Pass = (By.ID, 'password')
    quicklly = (By.XPATH, '/html/body/header/a/img')
    FName = (By.XPATH, '//*[@id="recipient_fname"]')
    LName = (By.XPATH, '//*[@id="recipient_lname"]')
    Email1 = (By.ID, 'recipient_email')
    PhoneNo = (By.ID, 'recipient_phone')
    Address = (By.XPATH, '//*[@id="autocomplete4"]')
    ApartmentNo = (By.XPATH, '//*[@id="recipient_appartment"]')
    Delieverytype = (By.XPATH, '//*[@id="frmRecipent"]/div[1]/div/div[7]/div[1]/p/input')
    SubmitButton = (By.ID, 'save_recipent')


def email_textbox_id():
    return None
